---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- path: content
  label: Pages
  create: all
- path: content/post
  label: Post
  create: all
- path: content/videos
  label: Videos
  create: all
- path: content/photos
  label: Photos
  create: all
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: 0.42.2
